### ISSUE TITLE
Method setFeaturesCols([class scala.collection.convert.Wrappers$JListWrapper]) does not exist

### ISSUE THREAD

**Issue by sdev2030** [NVIDIA/spark-xgboost-examples#14]
I am trying to run the sample mortgage notebook in spark 3.0 with Databricks 7.0 environment. 
Followed the steps mentioned in 7.0 initialization notebook.
Library install was successful for dbfs:/FileStore/jars/xgboost4j-spark_3.0-1.0.0-0.1.0.jar 
Any pointer to fix this will be helpful. Thanks

**Comment by wbo4958** [comment]
@firestarman Could you have a look at this issue?

**Comment by firestarman** [comment]
Which notebook did you use, Python or scala ?

**Comment by sdev2030** [comment]
I am using the Python notebook. Error is when creating XGBoost classifier. (4th command cell)
https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/examples/notebooks/python/mortgage-gpu.ipynb

**Comment by sdev2030** [comment]
Hi @firestarman,
I could get past the method not found error after redoing the initialization script and library install.
Now I am getting "IllegalArgumentException: features does not exist." error. Rapids-4-spark Libraries are installed successfully. Anything else I need to setup. Let me know. Thanks
<img width="1118" alt="Screen Shot 2020-07-21 at 11 39 10 AM" src="https://user-images.githubusercontent.com/52033527/88094499-8c4a8800-cb48-11ea-98cb-c6d07c90e212.png">

**Comment by wbo4958** [comment]
Please refer to 
https://github.com/NVIDIA/spark-xgboost-examples/issues/13#issuecomment-660917800
https://github.com/NVIDIA/spark-xgboost-examples/issues/13#issuecomment-661591433

**Comment by sdev2030** [comment]
Hi @wbo4958,
I followed the coding as suggested in issue #13 but it didn't solve the issue. Still getting "features does not exist" error.
<img width="721" alt="Screen Shot 2020-07-21 at 7 39 41 PM" src="https://user-images.githubusercontent.com/52033527/88128108-17983d80-cb8a-11ea-8720-44db17c9e02e.png">
Any thing else I need to change. Thanks for your support.

**Comment by wbo4958** [comment]
Hi @sdev2030, Could you check if rapids-4-spark jar has contained SQLPlugin, 

```
jar tf rapids-4-spark.jar | grep SQLPlugin
```

**Comment by sdev2030** [comment]
Hi @wbo4958,
I checked it in the folder where the "rapids-4-spark*.jar" file is there and SQLPlugin is in the jar. If I just put the command as you mention above, it fails. Should I be having rapids-4-spark.jar without version numbers. Let me know.
<img width="510" alt="Screen Shot 2020-07-21 at 9 50 07 PM" src="https://user-images.githubusercontent.com/52033527/88136020-41a72b00-cb9d-11ea-83c3-adfc6942c4cb.png">

**Comment by gnani4444** [comment]
Hi @wbo4958 @firestarman 
This is not relevant to this issue,  
Its from the [previous issue](https://github.com/NVIDIA/spark-xgboost-examples/issues/13#issuecomment-661830088)

Can you share any notebook or code for hyper-parameter tuning using hyperopt, If you already have it.

I couldn't find featureImportances method for the model object. Can you guide me how to get feature importances.

Thanks in Advance

**Comment by wbo4958** [comment]
> Hi @wbo4958,
> I checked it in the folder where the "rapids-4-spark*.jar" file is there and SQLPlugin is in the jar. If I just put the command as you mention above, it fails. Should I be having rapids-4-spark.jar without version numbers. Let me know.
> <img alt="Screen Shot 2020-07-21 at 9 50 07 PM" width="510" src="https://user-images.githubusercontent.com/52033527/88136020-41a72b00-cb9d-11ea-83c3-adfc6942c4cb.png">

Hi @sdev2030, Is there any history WebUI and paste Spark Properties of **Environment**

**Comment by wbo4958** [comment]
> Hi @wbo4958 @firestarman
> This is not relevant to this issue,
> Its from the [previous issue](https://github.com/NVIDIA/spark-xgboost-examples/issues/13#issuecomment-661830088)
> 
> Can you share any notebook or code for hyper-parameter tuning using hyperopt, If you already have it.
> 
> I couldn't find featureImportances method for the model object. Can you guide me how to get feature importances.
> 
> Thanks in Advance

Hi @gnani4444 Could you file another issue?

**Comment by gnani4444** [comment]
@sdev2030 
Can you add the conf directly to the cluster like below image in databricks cluster configuration. 

![image](https://user-images.githubusercontent.com/19526142/88139489-6d61f980-cc0d-11ea-8176-b493b9d55660.png)

**Comment by gnani4444** [comment]
> > Hi @wbo4958 @firestarman
> > This is not relevant to this issue,
> > Its from the [previous issue](https://github.com/NVIDIA/spark-xgboost-examples/issues/13#issuecomment-661830088)
> > Can you share any notebook or code for hyper-parameter tuning using hyperopt, If you already have it.
> > I couldn't find featureImportances method for the model object. Can you guide me how to get feature importances.
> > Thanks in Advance
> 
> Hi @gnani4444 Could you file another issue?

Hi @wbo4958 , I filed [another issue ](https://github.com/NVIDIA/spark-xgboost-examples/issues/16) here

**Comment by sdev2030** [comment]
Hi @wbo4958,
when I set the spark conf at the cluster level..I am getting a new error now. Is 7.0 stable...doubting that now!
<img width="135" alt="Screen Shot 2020-07-22 at 4 39 31 PM" src="https://user-images.githubusercontent.com/52033527/88240059-ea579800-cc3a-11ea-8ef6-9afcd85b36b9.png">

**Comment by gnani4444** [comment]
> Hi @wbo4958,
> when I set the spark conf at the cluster level..I am getting a new error now. Is 7.0 stable...doubting that now!

@sdev2030 Are you using Databricks runtime 7.0 **or** 7.0 ML **or** 7.0 ML GPU ?. Please make sure you are using 7.0 ML GPU.

**Comment by sdev2030** [comment]
Hi @wbo4958 @firestarman
Bit more progress. I was using p2 as worker node before, my apologies for missing to notice the m/c type before.
Once I switched the p3 for worker node, the training seems to fail at the 2nd stage. It appears like the processing goes thru fine and at the end it fails for some reason. I am attaching the errors. Please let me know if there is anything I need to change.
Thanks!
<img width="661" alt="Screen Shot 2020-07-24 at 10 15 26 AM" src="https://user-images.githubusercontent.com/52033527/88421678-cf516900-cd9d-11ea-96d6-bee01ff72c79.png">
[java error - gpu training.pdf](https://github.com/NVIDIA/spark-xgboost-examples/files/4973598/java.error.-.gpu.training.pdf)

**Comment by sdev2030** [comment]
Run time Java error were related to Databricks 7.0 GPU issue. Once it got resolved, the training worked.
I still need to set the spark configs at the cluster level for the notebook to work. Setting inside the notebook didn't work.
