### ISSUE TITLE
Lost Unique row Identifier after the prediction or transformation

### ISSUE THREAD

**Issue by gnani4444** [NVIDIA/spark-xgboost-examples#17]
Hi 
I am using XGBoost Spark 3.0 GPU version.

After transform or predict, the unique identifier or key is not available in the result data frame.

**Comment by sdev2030** [comment]
Hi @gnani4444, Did you find any workaround for this. Let us know.  Thanks

**Comment by GaryShen2008** [comment]
@wbo4958 Bobby, can you check this issue?
I wonder if the unique id or key is one of input columns when transforming.

@gnani4444 
Could you provide more details about what you did when transforming?
We skip some unsupported type of columns like string. But I think the unique id should be a numerical type, shouldn't it?

**Comment by wbo4958** [comment]
@gnani4444 @sdev2030 Could you provide your schema info?

**Comment by gnani4444** [comment]
Hi @GaryShen2008 , @wbo4958 

My unique row identifier is a string.

**Comment by sdev2030** [comment]
Hi @wbo4958, 

In my case Unique-Id column is "string" type and has alpha-numeric characters in it. 

I am used to seeing additional 3 columns (row_prediction, probability and prediction) added to the input data frame during transformation. Surprised to hear that "string" columns are ignored/dropped. Did not see it any where mentioned.
Please see whether you can keep all the columns in the input data frame after transformation.
If not, please update the documentation with the type of columns that will be ignored or dropped. 
Thanks for all the support.

**Comment by wbo4958** [comment]
Thx @gnani4444 @sdev2030, Yes, that's expected for now, since we have filtered out the StringType. That's because we were building Rows from GPU memory. For now the only fixed-length (StringType is not supported) type was supported. I will figure out a way to support StringType. Thx

**Comment by wbo4958** [comment]
Hi @gnani4444 @sdev2030 The simplest way to make it work is to specify the column data type of Row Identifier to LongType if possible.

**Comment by sdev2030** [comment]
Hi @wbo4958 
Yes, now that I know string type is not returned, I have added a long type column with unique numbers..After the transform, I add the column of original Row Identifier using the long type column as key for join. It is simple enough for now as a work around. Thanks for the support.

**Comment by wbo4958** [comment]
@sdev2030, Thx. We will support StringType in the next release.
