### ISSUE TITLE
How to configuration GPU?wasted resources?

### ISSUE THREAD

**Issue by justsheep** [NVIDIA/spark-xgboost-examples#22]
When I run the code, there is a WARN SparkContext:
`The configuration of resource: gpu (exec = 1, task = 1, runnable tasks = 1) will result in wasted resources due to resource  limiting the number of runnable tasks per executor to: -1. Please adjust your configuration.`
As a result, use GPU is slower than not use GPU.
How  to configuration GPU?

**Comment by wbo4958** [comment]
@justsheep Can you  share your configurations? like standalone/yarn, workers/ executors ...

**Comment by justsheep** [comment]
@wbo4958 
There are eight nodes, and one 2070super on each node.
I use standalone and configured it like this in my code:
`spark = SparkSession.builder.appName("test") \`
`.config("spark.driver.resource.gpu.discoveryScript", "/usr/local/spark/jars/getGpusResources.sh") \`
`.config("spark.driver.resource.gpu.amount", "1") \`
`.config("spark.executor.resource.gpu.discoveryScript", "/usr/local/spark/jars/getGpusResources.sh") \`
`.config("spark.executor.resource.gpu.amount", "1") \`
`.config("spark.task.resource.gpu.amount", "1") \`
`.getOrCreate()`

**Comment by wbo4958** [comment]
@justsheep Could you refer https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/docs/get-started/getting-started.md#spark-standalone-cluster to config?

**Comment by justsheep** [comment]
@wbo4958 
The GPU configuration warning was resolved, but a new error occurred:
`ERROR TaskSchedulerImpl: Lost an executor 11 (already removed): Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues.`
`......Lost an executor 12 (already removed)......`
`......Lost an executor 13 (already removed)......`
`......`
I didn't make any other changes and there are no errors when I don't use the GPU.

**Comment by wbo4958** [comment]
Seems the executor is always crashing.
you need to check the executor log. Could you pls paste your executor logs?

**Comment by justsheep** [comment]
I checked all the configurations carefully. Now the problem has been solved, thank you.😄
