### ISSUE TITLE
Broken Link in Kubernetes guide

### ISSUE THREAD

**Issue by davidwilliams921** [NVIDIA/spark-xgboost-examples#39]
**Describe the bug**
Pretty simple, broken link to the Dockerfile in the Kubernetes getting started guide. Broken link found here: https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/getting-started-guides/on-prem-cluster/kubernetes.md#build-a-gpu-spark-docker-image

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Comment by GaryShen2008** [comment]
Fix by https://github.com/NVIDIA/spark-xgboost-examples/pull/40
